### ISSUE TITLE
plotting function errors

### ISSUE THREAD

**Issue by rfarouni** [Mathelab/ALTRE#47] opened 2016-10-19 14:57 UTC
There are  argument is of length zero errors at these lines: 
plottingfunctions.R #177 
plottingfunctions.R #397
plottingfunctions.R#536

```
Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    81: plotCombineAnnotatePeaks [/home/rick/Documents/repos/ALTRE/R/plottingfunctions.R#177]
    80: renderUI [/home/rick/R/x86_64-pc-linux-gnu-library/3.3/ALTRE/shinyApp/server.R#302]
    79: func
    78: origRenderFunc
    77: output$annotatebarplot
     2: shiny::runApp
     1: runShinyApp [/home/rick/Documents/repos/ALTRE/R/runshiny.R#10]
Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics'
Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics'
Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics'
Found more than one class "connection" in cache; using the first, from namespace 'BiocGenerics'
Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    80: plotGetCounts [/home/rick/Documents/repos/ALTRE/R/plottingfunctions.R#397]
    79: func [/home/rick/R/x86_64-pc-linux-gnu-library/3.3/ALTRE/shinyApp/server.R#312]
    78: origRenderFunc
    77: output$densityplot
     2: shiny::runApp
     1: runShinyApp [/home/rick/Documents/repos/ALTRE/R/runshiny.R#10]

Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    81: plotCountAnalysis [/home/rick/Documents/repos/ALTRE/R/plottingfunctions.R#536]
```

**Comment by Mathelab** [comment] 2016-10-19 15:13
Why is this error only a problem with Shiny?  What is palette set to in the Shiny Call?
Ewy

**Comment by osubmi784323** [comment] 2016-10-19 15:17
I see what the problem is, I’ll fix. I’m not sure why it doesn’t show the error on the command line.

Liz

**Comment by Mathelab** [comment] 2016-10-19 15:19
What is the problem?
Ewy

**Comment by osubmi784323** [comment] 2016-10-19 17:14
Right now the function checks to see if a palette was specified or if the user wishes to manually enter their own palette argument. If palette is length 1 it assumes an R color brewer palette was entered. If it is of length four it assumes  colors have been entered. I though this was the problem — that Rshiny doesn’t like how the argument length has to be checked, but I used the viewer argument to prevent this argument from being checked in Rshiny (it could be ok to use palettes exclusively there…) and the error changed to being about Rcolorbrewer:

Warning: Error in if: argument is of length zero
Stack trace (innermost first):
    82: RColorBrewer::brewer.pal
    81: plotCountAnalysis
    80: renderUI [/Users/bask05/Library/R/3.3/library/ALTRE/shinyApp/server.R#322]
    79: func
    78: origRenderFunc
    77: output$volcano
     2: shiny::runApp
     1: runShinyApp

Is this new? Haven’t we been using Rcolorbrewer for a while now? I’m not sure how to address the error. Probably it is something to do with with how the palette input is input$palette4?

**Comment by rfarouni** [comment] 2016-10-19 18:01
Shiny side needs to have a default value in the argument, so there is nothing to be done there. At any rate, why do we want users to enter hex colors?  The previous solution that worked was this.

```
plotConsensusPeaks <- function(...., palette = NULL) {
  if ( !is.null(palette) ) {
    cols <- RColorBrewer::brewer.pal(3, palette)
  } else {
    cols <- RColorBrewer::brewer.pal(3, "Set1")
  }

```

**Comment by osubmi784323** [comment] 2016-10-19 18:04
Ewy wanted the ambiguous points on the volcano plot to be grey in the vignette. To be able to have that level of control, you need to be able to enter colors.

**Comment by rfarouni** [comment] 2016-10-19 18:39
Right won't make a difference since  we always have a character vector

```
str(RColorBrewer::brewer.pal(3, "Set1"))
 chr [1:3] "#E41A1C" "#377EB8" "#4DAF4A"
```

The shiny function sends the default palette but I think also a NULL if the object is not  yet available. You probably just need to handle this exception by adding  `!is.null(palette)`

**Comment by Mathelab** [comment] 2016-10-19 18:43
I think the error does come from the Shiny server side, that somehow the input is not set appropriately by default (even though it looks to be).

How about trying out something like this?

if (hex color)  {
…..
}
else if (allowable brewer.pal palette){
cols <- RColorBrewer::brewer.pal(3, palette)
}
else {cols <- RColorBrewer::brewer.pal(3, "Set1")t}

**Comment by rfarouni** [comment] 2016-10-19 18:56
In Shiny the function is called repeatedly not just once. Anytime there is an event or update on the screen, the function gets called. The first event is when the webpage first loads.There the object returned can be a NULL, but I haven't tested

**Comment by Mathelab** [comment] 2016-10-19 19:03
Ok Rick.  I thought that the function would not be called unless the getcountsObj() was returned as non-null (with the req() function).

So yes, checking for null should do the trick…

Ewy

**Comment by osubmi784323** [comment] 2016-10-20 13:28
Thanks, it worked, I pushed.

**Comment by Mathelab** [comment] 2016-10-20 13:31
OK thanks! will check it out soon and planning to resubmit by the end of the weekend…

Ewy

**Closed as completed** 2016-10-27 16:56 UTC
